### ISSUE TITLE
Up mass by year

### ISSUE THREAD

**Issue by myroslav** [r-spacex/spacexstats-react#1]
[u/Bailliesa](http://www.reddit.com/u/Bailliesa) in [SpaceX thread comment](http://www.reddit.com/r/spacex/comments/7953m5/rspacex_dev_community_and_update_of_spacex_stats/dozt4dt) requested feature:

> total up mass by year (similar to launches)

**Comment by AlbericTrancart** [comment]
Also with color distinction between orbit types
