### ISSUE TITLE
Minor Issue. No detection that launch time is in the past.

### ISSUE THREAD

**Issue by HarvsG** [r-spacex/spacexstats-react#18]
For example, today, where Zuma is was due to launch NOV 18TH, 1:00:00AM (UTC+00:00). Loading the website will say 1DAYS 13HOURS 41MINUTES 21SECONDS and then the clock will count down. When actually we are getting further away from the launch date, refreshing the page then demonstrates this.

Would it be possible to have a launch date calculation and counter that appreciated negative numbers and so could display the timer as overdue?

**Edit:**
I link this might be the responsible line
https://github.com/r-spacex/spacexstats-react/blob/dda933666ff8f20b3a88e99625fa7e2a4a6a6c70/app/components/stats/TimeStat.js#L46-L47

With the countdown timer written here:
https://github.com/r-spacex/spacexstats-react/blob/dda933666ff8f20b3a88e99625fa7e2a4a6a6c70/app/components/stats/TimeStat.js#L54-L73

Unfortunately, I don't have enough experience with react to fork, tweak this and test it myself. Although with the instructions on the README.md I may have a go when I get a moment!

**Comment by HarvsG** [comment]
I am trying to start the vagrant file with my VPS as the provider (digital ocean) an I am getting this error, is it to do with me or the or this repo?
```
    droplet1: Installing Ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.4.1.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    droplet1: Running ansible-playbook...
ERROR! the role 'nginx' was not found in /vagrant/devops/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/vagrant/devops

The error appears to have been in '/vagrant/devops/provision-dev.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - base
    - nginx
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by HarvsG** [comment]
I got it working in Docker.

1. Create a `Dockerfile` in the root directory 
2. the `Dockerfile`'s contents should be the below:
```
FROM node:carbon

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]
```
3. run $ `docker build -t <your docker username>/spacexstats .` (you can actually call it whatever you like
4. check it built with $ `docker images`
5. run it with $`docker run -p 49160:8080 -d <your docker username>/spacexstats`
6. Navigate to `localhost:49160` or if doing it on a remote machine (like I did) `<machine's ip adress>:49160`

Disclaimer: I am not experienced in containers so the above may be sub-optimal.

**Comment by vlinder** [comment]
Yes. It should now be counting up after reaching 0. It will still be positive though since I take the Math.abs() of the duration.
