### ISSUE TITLE
timelines falcon heavy

### ISSUE THREAD

**Issue by Aluriak** [r-spacex/spacexstats-react#23]
The last panel showing *Elon Musk's bet*, *Time since founding* and *Falcon Heavy* is a bit off for the *Falcon Heavy* slide, showing a launch in 5 days.

Or maybe it's the deadline given by an official ? The website is then unclear.

**Comment by MayeulC** [comment]
Well, it's *still* up there, in any case :D

**Comment by AlbericTrancart** [comment]
I will completely remove this tab for now. We'll surely find a new interesting one once we have more solid info on BFR/BFS :wink:
