### ISSUE TITLE
Hours worked

### ISSUE THREAD

**Issue by Aluriak** [r-spacex/spacexstats-react#24]
In the last panel (same as #23), the number of hours worked is *countless*. Beyond the joke, it would be interesting to put an estimation of man-hours put into the project.

**Comment by AlbericTrancart** [comment]
How are we supposed to do that? That's like answering the question "how many grains of sand went down  in an hourglass?" by "a lot". The estimation could be done for one point in time but updating it dynamically is a lot of hassle beyond the joke :wink:

**Comment by quadrplax** [comment]
Is there a source for the number of employees over time? If so, you could base it off of that, as well as an estimate of the weekly hours per employee.
