### ISSUE TITLE
Launch Count Total text blurb is incorrect

### ISSUE THREAD

**Issue by SEJeff** [r-spacex/spacexstats-react#27]
```
As of October 2017, SpaceX has launched 54 rockets, carrying a variety of payloads to multiple destinations;including LEO, GTO, L1, and the ISS. SpaceX currently has a manifest of over 70 flights that will fly over the coming years.
```

Pretty sure that should be `As of $MONTH_OF_LAST_LAUNCH_UPDATE`. Perhaps you could calculate the month of `turnaroundsData.lastLaunchDate` and just put that in place of the hardcoded month?

**Comment by brandtamos** [comment]
Fixed this one a couple weeks ago, gonna go ahead and mark this closed
