### ISSUE TITLE
Site is broken with https

### ISSUE THREAD

**Issue by Spudley** [r-spacex/spacexstats-react#28]
Hi. I just wanted to notify you that the spacexstats.xyz site does not work with https. It looks like there's a problem with your certificate setup, rather than simply not having a cert at all.

Error message in Chrome: ERR_SSL_PROTOCOL_ERROR

Error message in Firefox: SSL_ERROR_INTERNAL_ERROR_ALERT

**Comment by Patrickkk** [comment]
Also I would suggest forcing https to mitigate any MITM attacks

**Comment by AlbericTrancart** [comment]
@Patrickkk HTTPS should be enforced from now on.
@Spudley do you still have any certificate issue?

**Comment by Spudley** [comment]
Looks good to me. Thank you.
