### ISSUE TITLE
www required

### ISSUE THREAD

**Issue by Patrickkk** [r-spacex/spacexstats-react#30]
the site is no longer reachable under spacexstats.xyz www.spacexstats.xyz does still work. is this intentional?

**Comment by brandtamos** [comment]
Going to the root _should_ redirect you to www. I just tried that and it worked for me, but I can investigate if it's not working. 

I can't remember exactly why now, but I remember we had to use www because of how custom domains are configured in Heroku.

**Comment by Patrickkk** [comment]
I did some checking and on my phone it gets redirected to www.spacexstats.xyz, but nog on my desktop. I will try with a different computer tomorrow to see if it is related to my computer, I already tried to flush my DNS.

![image](https://user-images.githubusercontent.com/4058079/40589016-ebaa4e8e-61e6-11e8-8fdf-006d0166eb25.png)

**Comment by AlbericTrancart** [comment]
No updates on this issue, I'm closing it.
