### ISSUE TITLE
No doctype

### ISSUE THREAD

**Issue by NickSto** [r-spacex/spacexstats-react#42]
Hey, I noticed that the HTML returned by http://www.spacexstats.xyz/ doesn't start with a doctype (`<!DOCTYPE html>`).

I'm not familiar with React, so please close if I'm just missing something and it's intentional. But I thought it's generally a good idea to declare a doctype, or browsers will render it in quirks mode.

**Comment by AlbericTrancart** [comment]
You're right! I added it in [this commit](https://github.com/r-spacex/spacexstats-react/commit/1f690a2a19d8b15aa40d3c4450bfaab3cc7c615e).
