### ISSUE TITLE
Incorrect number of planned launches for 2018

### ISSUE THREAD

**Issue by quadrplax** [r-spacex/spacexstats-react#43]
The launch history graph still shows 10 planned launches as part of the initial goal of 30 for 2018, which obviously is not going to happen at this point. Planned launches should either be removed or be based on the launches/upcoming API endpoint to prevent this from being an issue in the future.

**Comment by jhpratt** [comment]
Looks like it's [this section](https://github.com/r-spacex/spacexstats-react/blob/master/app/helpers/launchHistory.js#L129-L142) in question. Could certainly be replaced with data from the API. @AlbericTrancart how hard would this be?

**Comment by AlbericTrancart** [comment]
Doable and a good idea, I will implement it soon :)
Also it will be nice to see planned launches after current year + 1

**Comment by AlbericTrancart** [comment]
Feature added in https://github.com/r-spacex/spacexstats-react/commit/7eb1689864496ce7b6fea0b7dc81faf2b728a5b6
