### ISSUE TITLE
Launch count comment "as of Invalid date"

### ISSUE THREAD

**Issue by lordpomeroy** [r-spacex/spacexstats-react#44]
`${format(turnarounds.lastLaunchDate, 'MMMM YYYY')}` in main.js line 52 returns an invalid date error that is then shown in the text. As of today the launch data for the last launch is for Iridium NEXT 8 (Launch 74) which includes a launch date in its JSON from the SpaceX-API. Therefore probably some date manipulation is done incorrectly.

**Comment by AlbericTrancart** [comment]
Should be fixed now
