### ISSUE TITLE
Incorrect number of Starlink satellites

### ISSUE THREAD

**Issue by quadrplax** [r-spacex/spacexstats-react#46]
The payloads section Starlink tab currently still shows 2 satellites when it should now be 62. This appears to be coming from a hard-coded "internetConstellation" variable in /app/helpers/payloads.js. I don't see any way this data could be pulled from the API currently as the number 60 is not anywhere in the data about the Starlink launch. Perhaps a temporary solution could be to count the number of launches containing "Starlink" in the mission_name, multiply by 60, and subtract 58 (for the Paz/Tin-Tin mission). This of course is not ideal as it assumes every launch from here on out will have 60 satellites, but it would be more correct than the current hard-coding.

**Comment by AlbericTrancart** [comment]
Temporary fix by modifying the constant done, will investigate which is the best the solution and if it can be done in the API

**Comment by quadrplax** [comment]
This problem is back now that SpaceX has had another Starlink launch. Since the counter is labeled "In Space", perhaps it would be best to get the number from a satellite database as some I think some of the first batch have already deorbited.

**Comment by AlbericTrancart** [comment]
This should be fixed, I renamed the label to "Sent in space" :)
