### ISSUE TITLE
Possibly wrong number of launches from Boca Chica

### ISSUE THREAD

**Issue by shahar603** [r-spacex/spacexstats-react#51]
![firefox_RmF0OqkIZc](https://user-images.githubusercontent.com/27346413/79694036-a8533a80-8276-11ea-9ae9-b3328e5e7be7.jpg)

Does the Starhopper 150m flight count as a launch. If it does, it should say 1 launch out of Boca Chica.

**Comment by AlbericTrancart** [comment]
I wouldn't count Starhopper hops as a launch. For Starship to count as a launch it will have to target orbit. (unless the r/spacex API will decide otherwise on another standard)
