### ISSUE TITLE
Launch history success rate launch #101 is in the wrong place in the chart

### ISSUE THREAD

**Issue by lordpomeroy** [r-spacex/spacexstats-react#64]
The launch number 101 is between launch 96 and 97.

![image](https://user-images.githubusercontent.com/18085819/96502483-23ab9e00-1252-11eb-82c9-06d17863ac6d.png)

Might be an issue with some underlying data but as far as i can see a sorting in successRate.ts should fix this.

**Comment by AlbericTrancart** [comment]
Thanks for the feedback! I've updated the chart. The flight number was based on SpaceX's mission number but now they are not launched in the same order those numbers are attributed. They launch too often!
