### ISSUE TITLE
Flight stats incorrect for reused dragon capsules in commercial crew section

### ISSUE THREAD

**Issue by MMeent** [r-spacex/spacexstats-react#86]
https://github.com/r-spacex/spacexstats-react/blob/master/src/components/blocks/Dragon/charts/commercialCrewFlights.ts#L34 incorrectly assumes that flight time of the `payload.dragon` is invalid when payload.reused is set, and thus defaults to 0.
I think that that is incorrect.

Currently, this means that flights with reused capsules are displayed as if they had 0 flight time, which is obviously incorrect.

**Comment by AlbericTrancart** [comment]
Good catch, this has been fixed since then!
