### ISSUE TITLE
Booster Reuse graph on hover has no linebreaks

### ISSUE THREAD

**Issue by JayBigGuy10** [r-spacex/spacexstats-react#99]
When hovering over the b1060, b1058 and b1051 sections in the reuse bar chart, their tool tips showing which missions they have launched are cut off as they are single lines which are longer than the divs they are contained in.

Add some line breaks, or make the list of missions bullet pointed?

**Comment by AlbericTrancart** [comment]
New issues emerge the more booster they launch!
Thanks for the feedback, it should be fixed now.
